source 'https://github.com/CocoaPods/Specs.git'

target 'TakePhotosAndRecordVideo' do
	
	platform :ios, '9.0'
	inhibit_all_warnings!  	
	use_frameworks!
  	pod 'Masonry', '~> 1.1.0'
  	pod 'BlocksKit', '~> 2.2.5'
  	pod 'SVProgressHUD', '~> 2.2.5'
end
